language: python
python:
  - "3.6"
before_install: 
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
  - pip3 install torchvision
  - pip install pandas numpy
script:
  - pytest -v --cov myDataPreProcess
  - coveralls
